### ISSUE TITLE
All sub sprites in the sprite asset get rendered when sprites.Length == 1

### ISSUE THREAD

**Issue by No3371** [fabriziospadaro/SpriteSheetRenderer#13]
![](https://user-images.githubusercontent.com/1814971/84988584-d5d43b80-b174-11ea-8fa5-738f173ca069.png)

![](https://user-images.githubusercontent.com/1814971/84988563-ce149700-b174-11ea-85d7-1a83bf393337.png)

**Comment by fabriziospadaro** [comment]
Thank you for the PR, really appreciate it!
