### ISSUE TITLE
Sprites not rendering unless the Camera FOV is Wide

### ISSUE THREAD

**Issue by AustinMustEat** [fabriziospadaro/SpriteSheetRenderer#7]
Hello,

Thanks for making such a great example. I'm having a strange issue where your example scene works great, and I can copy/paste the example MakeSpriteEntities to a blank scene and it works great, but if I copy/paste into my game scene the sprites only render if the camera is pulled very far back, or if the camera has a wide FoV. 

I have made sure no other objects are blocking the sprites due to sorting etc. The entity systems all appear to be running consistently either way. 

I know you can't dig into my game scene, but any technical reason come to mind why the camera or screen size might toggle the rendering on and off? 

Appreciate your thoughts as I've spent a good 10 hours trying to solve this one issue. Thank you either way!

**Comment by AustinMustEat** [comment]
Additional info - The issue appears to happen if you move the camera and MakeSpriteEntity GO anywhere other than the location you have them place in your example scene. Not sure why yet, but that's at the root of the problem. Any thoughts?

**Comment by fabriziospadaro** [comment]
@AustinMustEat Sorry for the late reply, this problem is generated by the shader and his way to play with the sorting layers and the z index.
I'm upgrading this project to the latest version of Unity ECS and I will fix this shader problem as soon as I can :D
