### ISSUE TITLE
Invalid stride 1 for Compute Buffer - must be greater than 0, less or equal to 2048 and a multiple of 4.

### ISSUE THREAD

**Issue by aganm** [fabriziospadaro/SpriteSheetRenderer#8]
I'm trying to use this in 2019.3 and getting this error. I'm clicking to find out where it is from, but it's not showing me anything. Can you help?

**Comment by RoryNickolls** [comment]
I found the cause of the issue in the `UpdateBuffers` function of SpriteSheetRenderer.cs. Changing the stride variable to `int stride = instanceCount >= 16 * SpriteSheetManager.renderInformation[renderIndex].spriteCount ? 4 : 16 * renderInformation.spriteCount;` fixed the issue for me, though I'm not sure if this is the best way.

**Comment by aganm** [comment]
@RoryNickolls  Thanks! That solved it.

**Comment by RoryNickolls** [comment]
Not sure what's happening there. Here's my stats for 1 million animated sprites moving around
[https://imgur.com/VnhX75g](url). Do you get any warnings that might explain it? I think I got one telling me to switch to .NET 4 first time round.

**Comment by fabriziospadaro** [comment]
> @RoryNickolls Thanks! That solved it. Now I have an other problem but no errors. I build the 1 million sprite scene and my CPU usage is high as if it's processing the sprites, but GPU is low and nothing on screen. Do you have an idea? Does building work for you?

Hey, as said in the read me you need .Net 4 to run this, hope this solves it, and let me know if you have any other problem

**Comment by aganm** [comment]
@fabriziospadaro  This bug is happening with .Net 4. Also I'm using Unity 2019.3.3. The process goes like: I open the BulkSpawnSprites[Demo] scene, play in editor works. CPU at ~80%, GPU ~50% and 1 million sprites at ~30fps. If I build the scene, CPU at 100%, GPU at 0%, no sprite on screen.

**Comment by fabriziospadaro** [comment]
Hello, I fixed the stride error and this fix should also solve the "no sprites on screen", let me know if you still get errors.
